2021-12-27 14:30:43,590 INFO    MainThread:11432 [internal.py:wandb_internal():90] W&B internal server running at pid: 11432, started at: 2021-12-27 14:30:43.589834
2021-12-27 14:30:43,592 INFO    WriterThread:11432 [datastore.py:open_for_write():77] open: C:\Users\leona\OneDrive\Desktop\CuriosityFramework\wandb\run-20211227_143042-3v9bqmd4\run-3v9bqmd4.wandb
2021-12-27 14:30:43,592 DEBUG   HandlerThread:11432 [handler.py:handle_request():130] handle_request: check_version
2021-12-27 14:30:43,597 DEBUG   SenderThread:11432 [sender.py:send():234] send: header
2021-12-27 14:30:43,597 DEBUG   SenderThread:11432 [sender.py:send_request():248] send_request: check_version
2021-12-27 14:30:43,692 DEBUG   SenderThread:11432 [sender.py:send():234] send: run
2021-12-27 14:30:44,019 DEBUG   HandlerThread:11432 [handler.py:handle_request():130] handle_request: run_start
2021-12-27 14:30:44,019 INFO    SenderThread:11432 [dir_watcher.py:__init__():169] watching files in: C:\Users\leona\OneDrive\Desktop\CuriosityFramework\wandb\run-20211227_143042-3v9bqmd4\files
2021-12-27 14:30:44,019 INFO    SenderThread:11432 [sender.py:_start_run_threads():807] run started: 3v9bqmd4 with start time 1640611842
2021-12-27 14:30:44,019 DEBUG   SenderThread:11432 [sender.py:send():234] send: summary
2021-12-27 14:30:44,037 INFO    SenderThread:11432 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2021-12-27 14:30:44,039 DEBUG   HandlerThread:11432 [meta.py:__init__():40] meta init
2021-12-27 14:30:44,039 DEBUG   HandlerThread:11432 [meta.py:__init__():54] meta init done
2021-12-27 14:30:44,040 DEBUG   HandlerThread:11432 [meta.py:probe():214] probe
2021-12-27 14:30:44,055 DEBUG   HandlerThread:11432 [meta.py:_save_pip():58] save pip
2021-12-27 14:30:44,055 DEBUG   HandlerThread:11432 [meta.py:_save_pip():72] save pip done
2021-12-27 14:30:44,055 DEBUG   HandlerThread:11432 [meta.py:_save_conda():79] save conda
2021-12-27 14:30:44,055 ERROR   HandlerThread:11432 [meta.py:_save_conda():88] Error saving conda packages
Traceback (most recent call last):
  File "C:\Users\leona\anaconda3\envs\cudaenv\lib\site-packages\wandb\sdk\internal\meta.py", line 85, in _save_conda
    ["conda", "env", "export"], stdout=f, stderr=subprocess.DEVNULL
  File "C:\Users\leona\anaconda3\envs\cudaenv\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\leona\anaconda3\envs\cudaenv\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\leona\anaconda3\envs\cudaenv\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
2021-12-27 14:30:44,055 DEBUG   HandlerThread:11432 [meta.py:_save_conda():89] save conda done
2021-12-27 14:30:44,055 DEBUG   HandlerThread:11432 [meta.py:probe():252] probe done
2021-12-27 14:30:44,088 DEBUG   SenderThread:11432 [sender.py:send():234] send: files
2021-12-27 14:30:44,088 INFO    SenderThread:11432 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2021-12-27 14:30:44,103 DEBUG   HandlerThread:11432 [handler.py:handle_request():130] handle_request: stop_status
2021-12-27 14:30:44,103 DEBUG   SenderThread:11432 [sender.py:send_request():248] send_request: stop_status
